controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  bipedal_controller:
    type: bipedal_robot/BipedalController
  init_joint_pos_controller:
    type: bipedal_robot/InitialJointController
    leg_l1_joint:
      pid: {p: 30.0, i: 0.0, d: 2.0}
    leg_l2_joint:
      pid: {p: 30.0, i: 0.0, d: 2.0}
    leg_l3_joint:
      pid: {p: 40.0, i: 0.0, d: 2.0}
    leg_l4_joint:
      pid: {p: 40.0, i: 0.0, d: 2.0}
    leg_l5_joint:
      pid: {p: 30.0, i: 0.0, d: 0.01}
    

