controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  bipedal_controller:
    type: bipedal_robot/BipedalController
  init_joint_pos_controller:
    type: bipedal_robot/InitialJointController
    joints:
      - leg_l1_joint
      - leg_l2_joint
      - leg_l3_joint
      - leg_l4_joint
      - leg_l5_joint
      - leg_r1_joint
      - leg_r2_joint
      - leg_r3_joint
      - leg_r4_joint
      - leg_r5_joint
    leg_l1_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_l2_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_l3_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_l4_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_l5_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_r1_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_r2_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_r3_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_r4_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    leg_r5_joint:
      pid: {p: 20.0, i: 0.0, d: 0.0}
    

