bipedal_mujoco:
  robot: h1
  robot_scene: scene.xml
  description_pkg: h1_description
  loop_frequency: 500
  cycle_time_error_threshold: 0.002
  thread_priority: 95
  imu:
    handle_name: base_imu
    frame_id: imu_link
    orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
    angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
    linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
    topic_name: imu_data
  base_link: pelvis   # it should align with the name in mujoco model